anguage: node_js
sudo: false
node_js:
- '5.1'

addons:
  apt:
    packages:
      - xvfb

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

before_script:
  - npm install