language: node_js
node_js:
  - "7"

#dist: trusty

cache:
  directories:
    - "node_modules"



#
addons:
  chrome: stable
#
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script: ./node_modules/karma/bin/karma start ./karma.conf.js
#  - export CHROME_BIN=/usr/bin/google-chrome
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3 # give xvfb some time to start
##  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#
#before_script:
#  - npm install


